name: "Experimental Release"

on:
  workflow_dispatch:
    inputs:
        branch:
          required: true
          type: string
        tag:
          required: true
          type: string
        description:
          required: false
          type: string

jobs:
  build_job:
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu20.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 1
      - uses: uraimo/run-on-arch-action@v2
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ github.token }}

          setup: |
            mkdir -p "${PWD}/artifacts"
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          env: | 
            artifact_name: git-${{ matrix.distro }}_${{ matrix.arch }}
          shell: /bin/sh

          install: |
            case "${{ matrix.distro }}" in
              ubuntu*|jessie|stretch|buster|bullseye)
                apt-get update -q -y
                apt-get install -y git
                apt-get install build-essential -y
                apt-get install libsdl2-dev -y
                apt-get install libncursesw5-dev -y
                apt-get install libsdl2-ttf-dev -y
                apt-get install libsdl2-image-dev -y
                apt-get install libsdl2-mixer-dev -y
                apt-get install libpulse-dev -y
                apt-get install gettext -y
                apt-get install parallel -y
                apt-get install libfreetype6-dev -y
                ;;
              fedora*)
                dnf -y update
                dnf -y install git which
                ;;
              alpine*)
                apk update
                apk add git
                ;;
            esac

          run: |
            gcc -v
            git clone --depth 1 --branch Tu-c https://github.com/Kilvoctu/Cataclysm-DDA.git
            cd Cataclysm-DDA
            make -j$((`nproc`+0)) TILES=1 SOUND=1 RELEASE=1 LOCALIZE=1 LANGUAGES=all LINTJSON=0 ASTYLE=0 RUNTESTS=0
            strip cataclysm-tiles
            cp cataclysm-tiles "/artifacts/${artifact_name}"
            echo "Produced artifact at /artifacts/${artifact_name}"
      
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ inputs.branch }}-${{ inputs.tag }}"
          artifacts: "cataclysm-tiles"
          body: ${{ inputs.description }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
