name: "Experimental Release"

on:
  workflow_dispatch:
    inputs:
        branch:
          required: true
          type: string
        tag:
          required: true
          type: string
        description:
          required: false
          type: string

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPOSITORY_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 1
      
      - name: Install dependencies
        run: |
          sudo apt install docker-ce docker-ce-cli containerd.io
          docker pull monkeyx/retro_builder:arm64
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --privileged -it --platform=linux/arm64 --name builder64 monkeyx/retro_builder:arm64 bash
          docker container start builder64
          git clone --depth 1 --branch Tu-c https://github.com/Kilvoctu/Cataclysm-DDA.git
          cd Cataclysm-DDA
          sudo apt install gettext

      - name: Build
        run: |
          make -j$((`nproc`+0)) TILES=1 SOUND=1 RELEASE=1 LOCALIZE=1 LANGUAGES=all
          strip cataclysm-tiles
          exit
          docker cp builder64:root/Cataclysm-DDA/cataclysm-tiles .

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ inputs.branch }}-${{ inputs.tag }}"
          artifacts: "cataclysm-tiles"
          body: ${{ inputs.description }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
