name: "Experimental Release"

on:
  workflow_dispatch:
    inputs:
        branch:
          required: true
          type: string
        tag:
          required: true
          type: string
        description:
          required: false
          type: string


jobs:
  aarch64_job:
    # The host should always be Linux
    runs-on: ubuntu-22.04
    name: Build on ubuntu-22.04 aarch64
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          fetch-depth: 1
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu22.04

          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
      
      - name: Get Dependencies
        run: |
          sudo apt-get update
          sudo apt install libsdl2-image-dev
          sudo apt install gettext

      - name: Build
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
          git clone --depth 1 --branch Tu-c https://github.com/Kilvoctu/Cataclysm-DDA.git
          cd Cataclysm-DDA
          make -j$((`nproc`+0)) TILES=1 SOUND=1 RELEASE=1 LOCALIZE=1 LANGUAGES=all
          strip cataclysm-tiles
      
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ inputs.branch }}-${{ inputs.tag }}"
          artifacts: "cataclysm-tiles"
          body: ${{ inputs.description }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
